============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-7.0.1, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /users/sanand14/torchrunx/tests, configfile: pytest.ini
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-7.0.1, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /users/sanand14/torchrunx/tests, configfile: pytest.ini
collecting ... collected 0 items / 1 error

==================================== ERRORS ====================================
___________________ ERROR collecting test_multinode_spawn.py ___________________
Fixture "mock_socket" called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
See https://docs.pytest.org/en/stable/explanation/fixtures.html for more information about fixtures, and
https://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code.
=============================== warnings summary ===============================
../../../../users/sanand14/.local/lib/python3.6/site-packages/_pytest/config/__init__.py:1249
  /users/sanand14/.local/lib/python3.6/site-packages/_pytest/config/__init__.py:1249: PytestConfigWarning: Unknown config option: python_paths
  
    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

../../../../users/sanand14/.local/lib/python3.6/site-packages/paramiko/transport.py:32
  /users/sanand14/.local/lib/python3.6/site-packages/paramiko/transport.py:32: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
    from cryptography.hazmat.backends import default_backend

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
ERROR ../../../../users/sanand14/torchrunx/tests/test_multinode_spawn.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 2 warnings, 1 error in 0.39s =========================
srun: error: node1317: task 0: Exited with exit code 2
collecting ... collected 0 items / 1 error

==================================== ERRORS ====================================
___________________ ERROR collecting test_multinode_spawn.py ___________________
Fixture "mock_socket" called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
See https://docs.pytest.org/en/stable/explanation/fixtures.html for more information about fixtures, and
https://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code.
=============================== warnings summary ===============================
../../../../users/sanand14/.local/lib/python3.6/site-packages/_pytest/config/__init__.py:1249
  /users/sanand14/.local/lib/python3.6/site-packages/_pytest/config/__init__.py:1249: PytestConfigWarning: Unknown config option: python_paths
  
    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

../../../../users/sanand14/.local/lib/python3.6/site-packages/paramiko/transport.py:32
  /users/sanand14/.local/lib/python3.6/site-packages/paramiko/transport.py:32: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
    from cryptography.hazmat.backends import default_backend

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
ERROR ../../../../users/sanand14/torchrunx/tests/test_multinode_spawn.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 2 warnings, 1 error in 0.61s =========================
srun: error: node1327: task 1: Exited with exit code 2
